apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  namespace: cattle-system
  name: rancher
  labels:
    app: rancher
    chart: rancher-2.4.0
    heritage: Helm
    release: rancher
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@qoffice.ro
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: traefik
