apiVersion: v1
kind: Service
metadata:
  name: vscode
  namespace: vscode
spec:
  clusterIP: None
  selector:
    app: vscode
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vscode
  namespace: vscode
spec:
  selector:
    matchLabels:
      app: vscode
  serviceName: vscode
  replicas: 1
  template:
    metadata:
      labels:
        app: vscode
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: vscode
        image: codercom/code-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
