apiVersion: v1
kind: Namespace
metadata:
  name: vscode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
  namespace: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: vscode
          image: codercom/code-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vscode
  namespace: vscode
spec:
  clusterIP: None
  selector:
    app: vscode
  ports:
    - port: 80
      targetPort: 8080
